# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Workspace\ScrapQT\UI\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1009, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1009, 650))
        MainWindow.setMaximumSize(QtCore.QSize(1009, 650))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-image: url(:/resource/Sign In - BG.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.LeftSide = QtWidgets.QVBoxLayout()
        self.LeftSide.setObjectName("LeftSide")
        spacerItem = QtWidgets.QSpacerItem(10, 180, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.LeftSide.addItem(spacerItem)
        self.scrap_logo = QtWidgets.QLabel(self.centralwidget)
        self.scrap_logo.setMaximumSize(QtCore.QSize(16777215, 150))
        self.scrap_logo.setStyleSheet("image: url(:/resource/ScrapQt.png);")
        self.scrap_logo.setText("")
        self.scrap_logo.setTextFormat(QtCore.Qt.AutoText)
        self.scrap_logo.setObjectName("scrap_logo")
        self.LeftSide.addWidget(self.scrap_logo)
        spacerItem1 = QtWidgets.QSpacerItem(20, 180, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.LeftSide.addItem(spacerItem1)
        self.gridLayout.addLayout(self.LeftSide, 2, 2, 1, 1)
        self.RightSide = QtWidgets.QVBoxLayout()
        self.RightSide.setObjectName("RightSide")
        spacerItem2 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.RightSide.addItem(spacerItem2)
        self.signin_title = QtWidgets.QLabel(self.centralwidget)
        self.signin_title.setMaximumSize(QtCore.QSize(16777215, 45))
        self.signin_title.setStyleSheet("font-family: \"Segoe UI\";\n"
"    font-weight: bold;\n"
"    font-style: normal;\n"
"    font-size: 40px;\n"
"    color: rgb(00,59,255);")
        self.signin_title.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.signin_title.setObjectName("signin_title")
        self.RightSide.addWidget(self.signin_title)
        self.action_line = QtWidgets.QLabel(self.centralwidget)
        self.action_line.setMaximumSize(QtCore.QSize(16777215, 25))
        self.action_line.setStyleSheet("font-family: \"Rockwell\";\n"
"font-style: italic;\n"
"font-size: 20px;\n"
"color: rgb(163, 174, 208);")
        self.action_line.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.action_line.setObjectName("action_line")
        self.RightSide.addWidget(self.action_line)
        self.signin_google = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signin_google.sizePolicy().hasHeightForWidth())
        self.signin_google.setSizePolicy(sizePolicy)
        self.signin_google.setMaximumSize(QtCore.QSize(410, 50))
        font = QtGui.QFont()
        font.setKerning(True)
        self.signin_google.setFont(font)
        self.signin_google.setStyleSheet("image: url(:/resource/Google.png);\n"
"border: none;")
        self.signin_google.setText("")
        self.signin_google.setObjectName("signin_google")
        self.RightSide.addWidget(self.signin_google)
        spacerItem3 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.RightSide.addItem(spacerItem3)
        self.email = QtWidgets.QLabel(self.centralwidget)
        self.email.setMaximumSize(QtCore.QSize(16777215, 25))
        self.email.setStyleSheet("font-family: \"Rockwell\";\n"
"font-weight: normal;\n"
"font-style: normal;\n"
"font-size: 20px;")
        self.email.setObjectName("email")
        self.RightSide.addWidget(self.email)
        self.email_enter = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_enter.sizePolicy().hasHeightForWidth())
        self.email_enter.setSizePolicy(sizePolicy)
        self.email_enter.setMinimumSize(QtCore.QSize(0, 40))
        self.email_enter.setStyleSheet("background-color: rgb(247, 247, 247);\n"
"border: none;\n"
"backfround-radius: 30px;\n"
"color: rgb(0,0,0);\n"
"font-size: 20px;\n"
"padding: 10px;\n"
"font-family: \"Segoe UI\";\n"
"    font-weight: normal;\n"
"    font-style: normal;")
        self.email_enter.setObjectName("email_enter")
        self.RightSide.addWidget(self.email_enter)
        self.password = QtWidgets.QLabel(self.centralwidget)
        self.password.setMaximumSize(QtCore.QSize(16777215, 25))
        self.password.setStyleSheet("font-family: \"Rockwell\";\n"
"font-weight: normal;\n"
"font-style: normal;\n"
"font-size: 20px;")
        self.password.setObjectName("password")
        self.RightSide.addWidget(self.password)
        self.password_enter = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_enter.sizePolicy().hasHeightForWidth())
        self.password_enter.setSizePolicy(sizePolicy)
        self.password_enter.setStyleSheet("background-color: rgb(247, 247, 247);\n"
"border: none;\n"
"backfround-radius: 30px;\n"
"color: rgb(0,0,0);\n"
"font-size: 20px;\n"
"padding: 10px;\n"
"font-family: \"Segoe UI\";\n"
"    font-weight: normal;\n"
"    font-style: normal;")
        self.password_enter.setObjectName("password_enter")
        self.RightSide.addWidget(self.password_enter)
        spacerItem4 = QtWidgets.QSpacerItem(5, 45, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.RightSide.addItem(spacerItem4)
        self.signin_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signin_button.sizePolicy().hasHeightForWidth())
        self.signin_button.setSizePolicy(sizePolicy)
        self.signin_button.setMaximumSize(QtCore.QSize(16777215, 50))
        self.signin_button.setStyleSheet("background-color: rgb(0, 89, 255);\n"
"border-radius: 40px;\n"
"color: rgb(255, 255, 255);\n"
"font-size: 20px;\n"
"padding: 10px;\n"
"font-family: \"Segoe UI\";\n"
"    font-weight: bold;\n"
"    font-style: normal;")
        self.signin_button.setFlat(False)
        self.signin_button.setObjectName("signin_button")
        self.RightSide.addWidget(self.signin_button)
        spacerItem5 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.RightSide.addItem(spacerItem5)
        self.gridLayout.addLayout(self.RightSide, 2, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 2, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 2, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 2, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signin_title.setText(_translate("MainWindow", "Sign In"))
        self.action_line.setText(_translate("MainWindow", "Enter your email and password to sign in!"))
        self.email.setText(_translate("MainWindow", "Email"))
        self.email_enter.setPlaceholderText(_translate("MainWindow", "Enter your email"))
        self.password.setText(_translate("MainWindow", "Password"))
        self.password_enter.setPlaceholderText(_translate("MainWindow", "Enter your password"))
        self.signin_button.setText(_translate("MainWindow", "Sign In"))
import asset_rc
